name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        rust:
          - stable
          - beta
          - nightly
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          targets: aarch64-linux-android, armv7-linux-androideabi
          components: rustfmt, clippy
      - name: Run build
        run: cargo install --path .
      - name: Run test
        working-directory: example
        run: cargo ndk -o jniLibs build -vv
      - name: Check code formatting
        continue-on-error: true
        run: cargo fmt --all -- --check
      - name: Run clippy
        continue-on-error: true
        run: cargo clippy -- -D warnings
